"""phase1 core schema

Revision ID: 6ce5fde6ce73
Revises: 
Create Date: 2026-05-17 16:35:00.567234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce5fde6ce73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_account_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('broker', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_account_id')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('asset_class', sa.Enum('STOCK', 'ETF', 'OPTION', name='assetclass'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('conid', sa.String(length=32), nullable=True),
    sa.Column('underlying_symbol', sa.String(length=64), nullable=True),
    sa.Column('option_type', sa.Enum('CALL', 'PUT', name='optiontype'), nullable=True),
    sa.Column('strike', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('PARSED', 'MANUAL', name='recordsource'), nullable=False),
    sa.Column('import_batch', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('flow_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'DIVIDEND', 'INTEREST', 'FEE', 'OTHER', name='cashflowtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate_to_usd', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('PARSED', 'MANUAL', name='recordsource'), nullable=False),
    sa.Column('import_batch', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('SPLIT', 'CASH_DIVIDEND', 'STOCK_DIVIDEND', 'MERGER', 'SPINOFF', 'SYMBOL_CHANGE', name='corporateactiontype'), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Enum('PARSED', 'MANUAL', name='recordsource'), nullable=False),
    sa.Column('import_batch', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('market_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('market_value_usd', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unrealized_pnl_usd', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'instrument_id', 'snapshot_date', name='uq_snapshot_account_instrument_date')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.String(length=64), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='tradeside'), nullable=False),
    sa.Column('open_close', sa.Enum('OPEN', 'CLOSE', name='openclose'), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('realized_pnl_ibkr', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate_to_usd', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('proceeds', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('proceeds_usd', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('commission_usd', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('PARSED', 'MANUAL', name='recordsource'), nullable=False),
    sa.Column('import_batch', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'trade_id', name='uq_trade_account_exec')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('positions_snapshot')
    op.drop_table('corporate_actions')
    op.drop_table('cash_flows')
    op.drop_table('instruments')
    op.drop_table('accounts')
    # ### end Alembic commands ###
